apiVersion: v1
kind: Pod
metadata:
  name: curly
spec:
  containers:
    - name: curl-client
      image: curlimages/curl
      command: ["/bin/sh","-c"]
      args:
        # added | tee /opt/curlresult so I could more easily test
        - sleep 5; watch -n 10 "curl -H '$SUPERSECRETHEADER' sinatra-service" | tee /opt/curlresult
      tty: true
      env:
        - name: SUPERSECRETHEADER
          # Changed to correct value
          value: "SUPERSECRETACCESSKEY: HTTP_SUPERSECRETACCESSKEY"
  nodeSelector:
    type: client